version: '3.8'

services:
    auth-nginx:
        container_name: auth-nginx
        image: nginx
        volumes:
            - "./conf:/etc/nginx/conf.d"
        ports:
            - "80:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"